basePath: /
definitions:
  controller.Camaba:
    properties:
      alamat:
        example: Parongpong Bandung
        type: string
      ktp:
        example: 320914299583999
        type: integer
      nama:
        example: Swagger
        type: string
      phone_number:
        example: "032313873183"
        type: string
    type: object
  controller.DaftarSekolah:
    properties:
      alamat:
        example: Parongpong Bandung
        type: string
      kdsekolah:
        example: 1000
        type: integer
      nama:
        example: Sekolah Swagger
        type: string
      phone_number:
        example: "086475678793"
        type: string
    type: object
  controller.JamKerja:
    properties:
      durasi:
        example: 8
        type: integer
      gmt:
        example: 7
        type: integer
      hari:
        example:
        - Senin
        - Selasa
        - Rabu
        - Kamis
        - Jumat
        - Sabtu
        - Minggu
        items:
          type: string
        type: array
      jam_keluar:
        example: "16:00"
        type: string
      jam_masuk:
        example: "08:00"
        type: string
      piket_tim:
        example: Piket Z
        type: string
      shift:
        example: 2
        type: integer
    type: object
  controller.Jurusan:
    properties:
      jenjang:
        example: Strata 1
        type: string
      kdjurusan:
        example: JS01
        type: string
      nama:
        example: Jurusan Swegger
        type: string
    type: object
  controller.Karyawan:
    properties:
      hari_kerja:
        example:
        - Senin
        - Selasa
        - Rabu
        - Kamis
        - Jumat
        - Sabtu
        - Minggu
        items:
          type: string
        type: array
      jabatan:
        example: Anonymous
        type: string
      jam_kerja:
        items:
          $ref: '#/definitions/controller.JamKerja'
        type: array
      nama:
        example: Tes Swagger
        type: string
      phone_number:
        example: "08123456789"
        type: string
    type: object
  controller.Pendaftaran:
    properties:
      aljurusan:
        example: Sedang Trend
        type: string
      alulbi:
        example: Universitas Internasional
        type: string
      asalsekolah:
        $ref: '#/definitions/controller.DaftarSekolah'
      biodata:
        $ref: '#/definitions/controller.Camaba'
      jalur:
        example: Prestasi
        type: string
      jurusan:
        $ref: '#/definitions/controller.Jurusan'
      kdpendaftar:
        example: 2306202301
        type: integer
      statuspendaftar:
        example: Terdaftar
        type: string
    type: object
  controller.Presensi:
    properties:
      biodata:
        $ref: '#/definitions/controller.Karyawan'
      checkin:
        description: Datetime     primitive.DateTime `bson:"datetime,omitempty" json:"datetime,omitempty"`
        example: MASUK
        type: string
      latitude:
        example: 123.11
        type: number
      location:
        example: Bandung
        type: string
      longitude:
        example: 123.11
        type: number
      phone_number:
        example: "08123456789"
        type: string
    type: object
host: ws-dito.herokuapp.com
info:
  contact:
    email: erditonaushaadam@gmail.com
    name: API Support
    url: https://github.com/erditona
  description: This is a sample server
  title: Swagger Example API
  version: "1.0"
paths:
  /delete-jurusan/{id}:
    delete:
      consumes:
      - application/json
      description: Hapus data jurusan.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Delete data jurusan.
      tags:
      - Penerimaan Mahasiswa Baru
  /delete-pendaftaran/{id}:
    delete:
      consumes:
      - application/json
      description: Hapus data pendaftaran.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Delete data pendaftaran.
      tags:
      - Penerimaan Mahasiswa Baru
  /delete-sekolah/{id}:
    delete:
      consumes:
      - application/json
      description: Hapus data sekolah.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Delete data sekolah.
      tags:
      - Penerimaan Mahasiswa Baru
  /delete/{id}:
    delete:
      consumes:
      - application/json
      description: Hapus data presensi.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Delete data presensi.
      tags:
      - Presensi
  /ins:
    post:
      consumes:
      - application/json
      description: Input data presensi.
      parameters:
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Presensi'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Presensi'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Insert data presensi.
      tags:
      - Presensi
  /ins-jurusan:
    post:
      consumes:
      - application/json
      description: Input data Jurusan.
      parameters:
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Jurusan'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Jurusan'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Insert data Jurusan.
      tags:
      - Penerimaan Mahasiswa Baru
  /ins-pendaftaran:
    post:
      consumes:
      - application/json
      description: Input data pendaftaran.
      parameters:
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Pendaftaran'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Pendaftaran'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Insert data pendaftaran.
      tags:
      - Penerimaan Mahasiswa Baru
  /ins-sekolah:
    post:
      consumes:
      - application/json
      description: Input data Sekolah.
      parameters:
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.DaftarSekolah'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.DaftarSekolah'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Insert data Sekolah.
      tags:
      - Penerimaan Mahasiswa Baru
  /jurusan:
    get:
      consumes:
      - application/json
      description: Mengambil semua data jurusan.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Jurusan'
      summary: Get All Data Jurusan.
      tags:
      - Penerimaan Mahasiswa Baru
  /jurusan/{id}:
    get:
      consumes:
      - application/json
      description: Ambil per ID data jurusan.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Jurusan'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get By ID Data Jurusan.
      tags:
      - Penerimaan Mahasiswa Baru
  /pendaftaran:
    get:
      consumes:
      - application/json
      description: Mengambil semua data pendaftaran.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Pendaftaran'
      summary: Get All Data Pendaftaran.
      tags:
      - Penerimaan Mahasiswa Baru
  /pendaftaran/{id}:
    get:
      consumes:
      - application/json
      description: Ambil per ID data pendaftaran.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Pendaftaran'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get By ID Data Pendaftaran.
      tags:
      - Penerimaan Mahasiswa Baru
  /pendaftaran/kd/{kdpendaftar}:
    get:
      consumes:
      - application/json
      description: Ambil per Kode data pendaftaran.
      parameters:
      - description: Masukan Kode Pendaftaran
        in: path
        name: kdpendaftar
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Pendaftaran'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get By Kode Pendaftar Data Pendaftaran.
      tags:
      - Penerimaan Mahasiswa Baru
  /presensi:
    get:
      consumes:
      - application/json
      description: Mengambil semua data presensi.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Presensi'
      summary: Get All Data Presensi.
      tags:
      - Presensi
  /presensi/{id}:
    get:
      consumes:
      - application/json
      description: Ambil per ID data presensi.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Presensi'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get By ID Data Presensi.
      tags:
      - Presensi
  /sekolah:
    get:
      consumes:
      - application/json
      description: Mengambil semua data sekolah.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.DaftarSekolah'
      summary: Get All Data Sekolah.
      tags:
      - Penerimaan Mahasiswa Baru
  /sekolah/{id}:
    get:
      consumes:
      - application/json
      description: Ambil per ID data sekolah.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.DaftarSekolah'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get By ID Data Sekolah.
      tags:
      - Penerimaan Mahasiswa Baru
  /upd-jurusan/{id}:
    put:
      consumes:
      - application/json
      description: Ubah data jurusan.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Jurusan'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Jurusan'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update data jurusan.
      tags:
      - Penerimaan Mahasiswa Baru
  /upd-pendaftaran/{id}:
    put:
      consumes:
      - application/json
      description: Ubah data pendaftaran.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Pendaftaran'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Pendaftaran'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update data pendaftaran.
      tags:
      - Penerimaan Mahasiswa Baru
  /upd-sekolah/{id}:
    put:
      consumes:
      - application/json
      description: Ubah data sekolah.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.DaftarSekolah'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.DaftarSekolah'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update data sekolah.
      tags:
      - Penerimaan Mahasiswa Baru
  /upd/{id}:
    put:
      consumes:
      - application/json
      description: Ubah data presensi.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Presensi'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Presensi'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update data presensi.
      tags:
      - Presensi
schemes:
- http
- https
swagger: "2.0"
