basePath: /api/v1
host: ws-dito.herokuapp.com
info:
  contact:
    email: erditonaushaadam@gmail.com
    name: API Support
    url: https://github.com/erditona
  description: This is a sample server
  title: Swagger Example API
  version: "1.0"
paths: {}
schemes:
- http
- https
swagger: "2.0"
